#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Skip prepare-commit-msg in CI environment
if [ "$CI" = "true" ]; then
	exit 0
fi

echo "🚦 PREPARE-COMMIT-MSG | Start cz with cz-customizable..."
exec </dev/tty && npx cz --hook || true
